/**
 * 
 */
package imago.image.plugins.file;

import java.io.File;
import java.io.IOException;

import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import imago.gui.FramePlugin;
import imago.gui.ImagoFrame;
import imago.image.ImageFrame;
import net.sci.image.Image;
import net.sci.image.io.VgiImageReader;

/**
 * Opens a dialog to read a file in VGI format, as generated by the VG Studio
 * Max software.
 * 
 * @author David Legland
 *
 */
public class ImportImageVgi implements FramePlugin
{
	public ImportImageVgi()
	{
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * java.awt.event.ActionListener#actionPerformed(java.awt.event.ActionEvent)
	 */
	@Override
	public void run(ImagoFrame frame, String args)
	{
        // opens a dialog to choose the file
	    FileFilter filter = new FileNameExtensionFilter("VGI files (*.vgi)", "vgi");
        File file = frame.getGui().chooseFileToOpen(frame, "Open VGI File", filter);
        
        // Check the chosen file is valid
        if (file == null || !file.isFile())
        {
            return;
        }
        
        // Create a MetaImage Format reader with the chosen file
        VgiImageReader reader;
        try
        {
            reader = new VgiImageReader(file);
        }
        catch (IOException ex)
        {
            System.err.println(ex);
            return;
        }
        
        // Try to read the image from the file
        Image image;
        try
        {
            image = reader.readImage();
        }
        catch (IOException ex)
        {
            System.err.println(ex);
            return;
        }
        catch (Exception ex)
        {
            System.err.println(ex);
            return;
        }
        
        // setup image metadata
        String fileName = file.getName();
        image.setNameFromFileName(fileName);


		// add the image document to GUI
        ImageFrame.create(image, frame);
	}
}
